<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class menuRepository extends EntityRepository
{
    public function getMenuByPlace($place)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder('t');
        $query = $qb->select('i.slug, i.title, i.id')
            ->from('AppBundle:Menu', 'm')
            ->join('m.information', 'i')
            ->where('m.place = :place')
            ->setParameter('place', $place)
            ->orderBy('m.sortOrder')
            ->getQuery();
        try {
            $result = $query->getResult();
        } catch (NoResultException $e) {
            $result = [];
        }
        return $result;
    }
}
